name: Myworkflow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  crt-wf-ubuntu:
    name: Lint code base in ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/evenodd.py 5 10 2 3

      - name: Every time
        run: echo "This step will always run"

  
  crt-wf-windows:
    name: Lint code base in windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/hwlloActions.py
  
