name: Myworkflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
        jake:
          description: 'Name of my friend'
          required: false
          default: 'Jake'

        jakes-eye-color:
          description: 'Eye color of the Jakes'
          required: true
          default: 'Blue' 


jobs:
  crt-wf-ubuntu:
    name: Check Even/Odd
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/evenodd.py 2 4

      - name: Every time
        run: echo "This step will always run"

  
  crt-wf-windows:
    name: Checking Prime number
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/prime.py 456


  crt-wf-macos:
    name: Using input and env context  
    env:
      DAY_OF_WEEK: Tuesday
      Greeting: Hello
      name: ${{ github.event.inputs.jake }}
      eye-color: ${{ github.event.inputs.jakes-eye-color }}


    runs-on: macos-latest
    steps:
      - name: "Say Hello, it's Monday"
        env:
          First_Name: Sanyam

        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "Hii $name,"
          echo "I like your eye colour ${eye-color}."