name: Myworkflow

on:
  push:
    branches: [ "master" ]

jobs:
  crt-wf-ubuntu:
    name: Check Even/Odd
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/evenodd.py 2 4

      - name: Every time
        run: echo "This step will always run"

  
  crt-wf-windows:
    name: Checking Prime number
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python scripts/prime.py
  
