name: Myworkflow

on: push

jobs:
  crt-wf:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'